version: 3

tasks:
  build-go:
    desc: Build go code
    cmds:
      - go build ./...
  test-go:
    desc: Test go code
    cmds:
      - go test -parallel 8 -v ./...
  proto:
    desc: Generate protobuf files
    cmds:
      - fd -t f -e proto -0 | xargs -0 protoc -I proto --go_out=go/protonats --go_opt=paths=source_relative --java_out=java/src/main/protobuf
