// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protonats.proto
// Protobuf Java Version: 4.29.3

package com.xiamli.protonats;

public final class ProtoNATS {
  private ProtoNATS() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ProtoNATS.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.xiamli.protonats.ProtoNATS.broadcast);
    registry.add(com.xiamli.protonats.ProtoNATS.consensusTarget);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * ConsensusTarget is an enum used to specify the target of a consensus-based operation.
   * </pre>
   *
   * Protobuf enum {@code protonats.ConsensusTarget}
   */
  public enum ConsensusTarget
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FOLLOWER = 0;</code>
     */
    FOLLOWER(0),
    /**
     * <code>LEADER = 1;</code>
     */
    LEADER(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ConsensusTarget.class.getName());
    }
    /**
     * <code>FOLLOWER = 0;</code>
     */
    public static final int FOLLOWER_VALUE = 0;
    /**
     * <code>LEADER = 1;</code>
     */
    public static final int LEADER_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConsensusTarget valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ConsensusTarget forNumber(int value) {
      switch (value) {
        case 0: return FOLLOWER;
        case 1: return LEADER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConsensusTarget>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ConsensusTarget> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConsensusTarget>() {
            public ConsensusTarget findValueByNumber(int number) {
              return ConsensusTarget.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xiamli.protonats.ProtoNATS.getDescriptor().getEnumTypes().get(0);
    }

    private static final ConsensusTarget[] VALUES = values();

    public static ConsensusTarget valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ConsensusTarget(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protonats.ConsensusTarget)
  }

  public static final int BROADCAST_FIELD_NUMBER = 526714442;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> broadcast = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int CONSENSUS_TARGET_FIELD_NUMBER = 526714443;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      com.xiamli.protonats.ProtoNATS.ConsensusTarget> consensusTarget = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.xiamli.protonats.ProtoNATS.ConsensusTarget.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017protonats.proto\022\tprotonats\032 google/pro" +
      "tobuf/descriptor.proto*+\n\017ConsensusTarge" +
      "t\022\014\n\010FOLLOWER\020\000\022\n\n\006LEADER\020\001:5\n\tbroadcast" +
      "\022\036.google.protobuf.MethodOptions\030\312\214\224\373\001 \001" +
      "(\010:X\n\020consensus_target\022\036.google.protobuf" +
      ".MethodOptions\030\313\214\224\373\001 \001(\0162\032.protonats.Con" +
      "sensusTargetBA\n\024com.xiamli.protonatsB\tPr" +
      "otoNATSZ\036xiam.li/protonats/go;protonatsb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    broadcast.internalInit(descriptor.getExtensions().get(0));
    consensusTarget.internalInit(descriptor.getExtensions().get(1));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
